import { Clipboard, Download, FileCheck2, History, Save, Send, Trash2, X } from "lucide-react";
import { useMemo, useState } from "react";
import type {
  AnomalyEvent,
  BriefHistoryItem,
  CareFlowInsight,
  DepartmentSignal,
  HospitalSnapshot,
  SuggestedAction,
} from "../types";

interface ActionBriefCardProps {
  snapshot: HospitalSnapshot;
  insight: CareFlowInsight;
  selectedInsights: CareFlowInsight[];
  selectedActions: SuggestedAction[];
  selectedAnomalies: AnomalyEvent[];
  selectedDepartments: DepartmentSignal[];
  history: BriefHistoryItem[];
  onRemoveInsight: (insight: CareFlowInsight) => void;
  onRemoveAction: (action: SuggestedAction) => void;
  onRemoveAnomaly: (anomaly: AnomalyEvent) => void;
  onRemoveDepartment: (department: DepartmentSignal) => void;
  onClose: () => void;
}

export function ActionBriefCard({
  snapshot,
  insight,
  selectedInsights,
  selectedActions,
  selectedAnomalies,
  selectedDepartments,
  history,
  onRemoveInsight,
  onRemoveAction,
  onRemoveAnomaly,
  onRemoveDepartment,
  onClose,
}: ActionBriefCardProps) {
  const [status, setStatus] = useState<string | null>(null);

  const briefText = useMemo(() => {
    const followUps = selectedActions.length
      ? selectedActions.map((action) => `- ${action.briefText}`).join("\n")
      : "- No follow-up items added yet.";
    const insightText = selectedInsights.length
      ? selectedInsights.map((item) => `- ${item.title}: ${item.summary}`).join("\n")
      : "- No primary insight summary added yet.";
    const anomalyText = selectedAnomalies.length
      ? selectedAnomalies.map((anomaly) => `- ${anomaly.briefText}`).join("\n")
      : "- No important anomaly added to this brief.";
    const departmentText = selectedDepartments.length
      ? selectedDepartments
          .map((department) => `- ${department.name}: ${department.summary} (${department.bottleneckRole})`)
          .join("\n")
      : "- No department finding added yet.";

    return [
      "11:00 Hospital Flow Brief",
      snapshot.hospitalName,
      `Generated by CareFlow at ${snapshot.snapshotTime}`,
      "",
      "Primary insight summary:",
      insightText,
      "",
      "Suggested follow-up:",
      followUps,
      "",
      "Department findings:",
      departmentText,
      "",
      "Operational watchouts:",
      anomalyText,
      "",
      `Safety note: ${insight.safetyNote}`,
    ].join("\n");
  }, [insight, selectedActions, selectedAnomalies, selectedDepartments, selectedInsights, snapshot]);

  const copyBrief = async () => {
    try {
      await navigator.clipboard.writeText(briefText);
      setStatus("Brief copied");
    } catch {
      setStatus("Brief ready");
    }
  };

  const markPrepared = (label: string) => {
    setStatus(label);
  };

  return (
    <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/30 backdrop-blur-sm" onClick={onClose}>
      <aside
        className="h-full w-full max-w-3xl overflow-y-auto bg-slate-50 p-6 shadow-2xl"
        onClick={(event) => event.stopPropagation()}
      >
        <div className="flex items-start justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-ai-soft text-ai">
              <FileCheck2 className="h-5 w-5" />
            </div>
            <div>
              <p className="text-sm font-bold uppercase tracking-wide text-ai">Human-readable output</p>
              <h2 className="text-2xl font-bold text-ink">Action Brief</h2>
            </div>
          </div>
          <button
            type="button"
            aria-label="Close action brief"
            onClick={onClose}
            className="flex h-10 w-10 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-500 transition hover:border-cyan-200 hover:text-ai"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="mt-6 rounded-3xl border border-slate-200 bg-white p-8 shadow-soft">
          <div className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-200 pb-5">
            <div>
              <p className="text-sm font-bold text-ai">11:00 Hospital Flow Brief</p>
              <h3 className="mt-2 text-3xl font-bold text-ink">{snapshot.hospitalName}</h3>
              <p className="mt-2 text-sm text-slate-500">
                {snapshot.snapshotTime} | {snapshot.scenarioName} | Generated by CareFlow
              </p>
            </div>
            <span className="rounded-full bg-ai-soft px-3 py-1.5 text-xs font-bold text-ai">
              Coordination support only
            </span>
          </div>

          <BriefSection title="Brief context">
            {`${insight.visibleProblem} Main bottleneck: ${insight.mainBottleneck}. Departments involved: ${insight.departmentsInvolved.join(", ")}.`}
          </BriefSection>

          <section className="mt-6">
            <h4 className="text-sm font-bold uppercase tracking-wide text-slate-500">Primary insight summary</h4>
            <div className="mt-3 space-y-3">
              {selectedInsights.length ? (
                selectedInsights.map((item) => (
                  <div key={item.id} className="rounded-2xl bg-cyan-50/70 p-4">
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <p className="font-bold text-ink">{item.title}</p>
                        <p className="mt-1 text-sm leading-6 text-slate-700">{item.summary}</p>
                        <p className="mt-2 text-xs font-semibold text-ai">
                          {item.trend} | Updated {item.lastUpdatedAt} | {item.confidence}
                        </p>
                      </div>
                      <button
                        type="button"
                        onClick={() => onRemoveInsight(item)}
                        className="inline-flex shrink-0 items-center gap-2 rounded-xl border border-cyan-200 bg-white px-3 py-2 text-xs font-bold text-ai transition hover:bg-cyan-50"
                      >
                        <Trash2 className="h-4 w-4" />
                        Remove
                      </button>
                    </div>
                  </div>
                ))
              ) : (
                <div className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-600">
                  Add the primary bottleneck summary from the dashboard when it needs to appear in the brief.
                </div>
              )}
            </div>
          </section>

          <section className="mt-6">
            <h4 className="text-sm font-bold uppercase tracking-wide text-slate-500">Suggested follow-up</h4>
            <div className="mt-3 space-y-3">
              {selectedActions.length ? (
                selectedActions.map((action) => (
                  <div key={action.id} className="rounded-2xl bg-slate-50 p-4">
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <p className="font-bold text-ink">{action.ownerRole}</p>
                        <p className="mt-1 text-sm leading-6 text-slate-700">{action.briefText}</p>
                        <p className="mt-2 text-xs font-semibold text-ai">
                          Est. time saved: {action.estimatedTimeSavedMinutes} minutes | Affected patients:{" "}
                          {action.affectedPatients}
                        </p>
                      </div>
                      <button
                        type="button"
                        onClick={() => onRemoveAction(action)}
                        className="inline-flex shrink-0 items-center gap-2 rounded-xl border border-red-100 bg-white px-3 py-2 text-xs font-bold text-red-600 transition hover:bg-red-50"
                      >
                        <Trash2 className="h-4 w-4" />
                        Remove
                      </button>
                    </div>
                  </div>
                ))
              ) : (
                <div className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-600">
                  Add suggested actions from the dashboard to build the brief.
                </div>
              )}
            </div>
          </section>

          <section className="mt-6">
            <h4 className="text-sm font-bold uppercase tracking-wide text-slate-500">Operational watchouts</h4>
            <div className="mt-3 space-y-3">
              {selectedAnomalies.length ? (
                selectedAnomalies.map((anomaly) => (
                  <div key={anomaly.id} className="rounded-2xl bg-amber-50 p-4 text-amber-900">
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <p className="font-bold">{anomaly.title}</p>
                        <p className="mt-1 text-sm leading-6">{anomaly.briefText}</p>
                      </div>
                      <button
                        type="button"
                        onClick={() => onRemoveAnomaly(anomaly)}
                        className="inline-flex shrink-0 items-center gap-2 rounded-xl border border-amber-200 bg-white px-3 py-2 text-xs font-bold text-amber-700 transition hover:bg-amber-100"
                      >
                        <Trash2 className="h-4 w-4" />
                        Remove
                      </button>
                    </div>
                  </div>
                ))
              ) : (
                <div className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-600">
                  No important anomaly added to this brief.
                </div>
              )}
            </div>
          </section>

          <section className="mt-6">
            <h4 className="text-sm font-bold uppercase tracking-wide text-slate-500">Department findings</h4>
            <div className="mt-3 space-y-3">
              {selectedDepartments.length ? (
                selectedDepartments.map((department) => (
                  <div key={department.id} className="rounded-2xl bg-slate-50 p-4">
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <p className="font-bold text-ink">{department.name}</p>
                        <p className="mt-1 text-sm leading-6 text-slate-700">{department.summary}</p>
                        <p className="mt-2 text-xs font-semibold text-ai">
                          {department.bottleneckRole} | {department.affectedPatients} patients | Updated{" "}
                          {department.lastUpdatedAt}
                        </p>
                      </div>
                      <button
                        type="button"
                        onClick={() => onRemoveDepartment(department)}
                        className="inline-flex shrink-0 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-700 transition hover:border-cyan-200 hover:text-ai"
                      >
                        <Trash2 className="h-4 w-4" />
                        Remove
                      </button>
                    </div>
                  </div>
                ))
              ) : (
                <div className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-600">
                  Add a department finding from a department detail drawer when it should be tracked.
                </div>
              )}
            </div>
          </section>

          <section className="mt-6 rounded-2xl border border-cyan-100 bg-cyan-50/70 p-4">
            <h4 className="text-sm font-bold uppercase tracking-wide text-ai">Safety note</h4>
            <p className="mt-2 text-sm leading-6 text-slate-700">{insight.safetyNote}</p>
          </section>
        </div>

        <div className="mt-5 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
          <div className="grid gap-3 sm:grid-cols-4">
            <button
              type="button"
              onClick={copyBrief}
              className="inline-flex items-center justify-center gap-2 rounded-xl bg-ai px-3 py-3 text-sm font-bold text-white transition hover:bg-cyan-700"
            >
              <Clipboard className="h-4 w-4" />
              Copy summary
            </button>
            <button
              type="button"
              onClick={() => markPrepared("PDF export prepared")}
              className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 py-3 text-sm font-bold text-slate-700 transition hover:border-cyan-200 hover:text-ai"
            >
              <Download className="h-4 w-4" />
              Export PDF
            </button>
            <button
              type="button"
              onClick={() => markPrepared("Marked ready for shift review")}
              className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 py-3 text-sm font-bold text-slate-700 transition hover:border-cyan-200 hover:text-ai"
            >
              <Send className="h-4 w-4" />
              Mark ready
            </button>
            <button
              type="button"
              onClick={() => markPrepared("Snapshot saved")}
              className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 py-3 text-sm font-bold text-slate-700 transition hover:border-cyan-200 hover:text-ai"
            >
              <Save className="h-4 w-4" />
              Save snapshot
            </button>
          </div>
          {status ? <p className="mt-3 text-sm font-semibold text-ai">{status}</p> : null}
        </div>

        <div className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
          <div className="flex items-center gap-2">
            <History className="h-5 w-5 text-ai" />
            <h3 className="text-lg font-bold text-ink">Brief History</h3>
          </div>
          <p className="mt-1 text-sm text-slate-500">
            Tracks what was added or removed so humans can audit the brief trail.
          </p>
          <div className="mt-4 space-y-3">
            {history.length ? (
              history.map((item) => (
                <div key={item.id} className="flex items-start justify-between gap-3 rounded-2xl bg-slate-50 p-4">
                  <div>
                    <p className="text-sm font-bold text-ink">{item.itemTitle}</p>
                    <p className="mt-1 text-xs font-semibold text-slate-500">{item.itemType}</p>
                  </div>
                  <div className="text-right">
                    <span
                      className={[
                        "rounded-full px-2 py-1 text-xs font-bold",
                        item.event === "Added" ? "bg-green-50 text-green-700" : "bg-red-50 text-red-700",
                      ].join(" ")}
                    >
                      {item.event}
                    </span>
                    <p className="mt-2 text-xs font-semibold text-slate-500">
                      {item.actor} | {item.timestamp}
                    </p>
                  </div>
                </div>
              ))
            ) : (
              <div className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-600">
                No brief changes yet.
              </div>
            )}
          </div>
        </div>
      </aside>
    </div>
  );
}

interface BriefSectionProps {
  title: string;
  children: string;
}

function BriefSection({ title, children }: BriefSectionProps) {
  return (
    <section className="mt-6">
      <h4 className="text-sm font-bold uppercase tracking-wide text-slate-500">{title}</h4>
      <p className="mt-2 text-base leading-7 text-slate-700">{children}</p>
    </section>
  );
}
